version: '3'

services:
 web:
   build: ./web
   restart: always
   expose:
     - "8000"
   volumes:
     - ./web:/home/flask/app/web
   depends_on:
     - redis
     - postgres
   links:
     - redis
     - postgres
   environment:
     FLASK_DEBUG: 1

 api:
   build: ./api
   restart: always
   expose:
     - "8001"
   volumes:
     - ./api:/home/api
   links:
     - web

 redis:
   image: redis:alpine
   restart: always
   deploy:
     mode: replicated
     replicas: 3

 nginx:
   build: nginx/
   restart: always
   ports:
     - "80:80"
   deploy:
     mode: replicated
     replicas: 3
   depends_on:
     - web
     - api

 postgres:
   restart: always
   image: postgres
   volumes:
     - ./postgres/init.sql:/docker-entrypoint-initdb.d/init.sql
     - ./postgres/data:/var/lib/postgresql/data
   environment:
     POSTGRES_PASSWORD: dockerdemo
     POSTGRES_DB: core-app
   expose:
     - "5432"